trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name='create'),
    path('daily_view/', views.select_day, name='daily_view'),
    path('confirm/<int:user_id>', views.confirm, name='confirm')
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (fo
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models

# Create your models here.

# TODO: Create an Employee model with properties required by the user stories

class Employee(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    street_address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=5)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)

trash_collector/employees/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.apps import apps
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from .models import Employee
from datetime import date
from datetime import datetime

# Create your views here.

# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.

def index(request):
    user = request.user
    Customer = apps.get_model('customers.Customer')
    pickup_customers = Customer.objects.all()
    try:
        logged_in_employee = Employee.objects.get(user=user)
    except Employee.DoesNotExist:
        return HttpResponseRedirect(reverse('employees:create'))
    context = {
            "pickup_customers": pickup_customers,
            "logged_in_employee":logged_in_employee
        }
    return render(request, 'employees/index.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        user = request.user
        zip_code = request.POST.get('zip_code')
        new_employee = Employee(name=name, user=user, zip_code=zip_code)
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/create.html')

def confirm(request, user_id):
    Customers = apps.get_model('customers.Customer')
    charge_customer = Customers.objects.get(pk = user_id)
    context = { 'charge_customer': charge_customer}
    if request.method == 'POST':
        charge_customer.balance += 10
        charge_customer.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/confirm.html', context)

def select_day(request):
    user = request.user
    logged_in_employee = Employee.objects.get(user=user)
    Customers = apps.get_model('customers.Customer')
    pickup_customers = Customers.objects.all()
    current_day = str(date.today())
    weekday = request.POST.get('day_of_the_week')
    pickups = []

    for customer in pickup_customers: 
        customer_start_suspension = str(customer.start_suspension)
        customer_end_suspension = str(customer.end_suspension)
        if  current_day < customer_start_suspension or current_day > customer_end_suspension:     
            if customer.zip_code == logged_in_employee.zip_code and (customer.weekly_pickup_date == weekday or customer.extra_pickup_date == weekday) :
                pickups.append(customer)

    context = { 'pickups': pickups,
                'pickup_customers': pickup_customers,
                'weekday': weekday
    }
    #if request.method == 'POST':
        #return('employees:confirm')
    return render(request, 'employees/daily_view.html', context)

trash_collector/employees/templates/employees/confirm.html
{% extends 'base.html' %}


{% block title %} Confirm Pickup {% endblock %}

{% block header %} Confirm Pickup {% endblock %}

{% block content %}

<form action="{% url 'employees:confirm' charge_customer.id %}" method='POST'>
    {% csrf_token %}
    <h2> Confirm pickup for {{charge_customer.name}} at {{charge_customer.street_address}} </h2>
    Confirm: <input type = 'checkbox' name='balance' id ='balance'><br>
    <br>
    <input type = 'submit' value = 'Charge Customer'>
</form>

{% endblock %}

trash_collector/employees/templates/employees/create.html
{% extends 'base.html' %}

{% block title %} Employee Create {% endblock %}

{% block header %} Employee Create {% endblock %}

{% block content %}
<form action="{% url 'employees:create' %}" method="post">
    {% csrf_token %}  
    Name: <input type="text" name='name' id='name'><br />
    Email: <input type="text" name='email' id='email'><br />
    Street Address: <input type="text" name='street_address' id='street_address'><br />
    City: <input type="text" name='city' id='city'><br />
    State: <input type="text" name='state' id='state'><br />
    Zip Code: <input type="text"name='zip_code' id='zip_code'><br />
<input type="submit" value="Submit">
</form>
{% endblock %}

trash_collector/employees/templates/employees/daily_view.html
{% extends 'base.html' %}

{% block title %} Employee Daily View {% endblock %}
{% block header %} <h1>Employee Daily View</h1> {% endblock %}

{% block content %}
<br>
<form action="{% url 'employees:daily_view'  %}" name="charge_customer" id="charge_customer" method='POST'>
    {% csrf_token %}
<div class="container" style="text-align: center">
        <div class="row">
            <div div class="col-md">
                <h5 style="text-align: center;">Customers on Your Pickup Route Today</h5>
                <hr>
                <div class="filter" style="text-align: right">
                    <form action="{% url 'employees:daily_view' %}" method='POST'>
                        {% csrf_token %}
                        <form action = "{% url 'employees:daily_view'%}" name = 'daily_view' id= 'daily_view' method = 'POST'>
                         <select name = "day_of_the_week" id = "day_of_the_week">
                            <option value = 'Monday' selected = "Monday">Monday</option>
                            <option value = 'Tuesday' selected = "Tuesday">Tuesday</option>
                            <option value = 'Wednesday' selected = "Wednesday">Wednesday</option>
                            <option value = 'Thursday' selected = "Thursday">Thursday</option>
                            <option value = 'Friday' selected = "Friday">Friday</option>
                        </select>
                        <input type = "submit" value = "Submit"> 
                    </form>
                </form>
                </div>
                <div class="card card-body">
                    <table class="table table-sm">
                        <thead class="thead-dark">
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Steet Address</th>
                            <th>City</th>
                            <th>State</th>
                            <th>Zip Code</th>
                            <th>Weekly Pickup Date</th>
                            <th>Balance</th>
                            <th>Confirm Pickup</th>
                        </tr>
                        <tbody>
                            {% for customer in pickup_customers %}
                        <tr>
                            <td>{{ customer.name }}</td>
                            <td>{{ customer.email }}</td>
                            <td>{{ customer.street_address }}</td>
                            <td>{{ customer.city }}</td>
                            <td>{{ customer.state }}</td>
                            <td>{{ customer.zip_code }}</td>
                            <td>{{ customer.weekly_pickup_date }}</td>
                            <td>${{ customer.current_balance }}</td>
                            <td><input type = 'submit' value='Confirm'></td>
                        </tr>
                        {% endfor %}
                        </tbody> 
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %} Employee Home {% endblock %}
{% block header %}<h1> Employee Home </h1>{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
<div class="container" style="text-align: center">
  <H1>Hello Employee {{ user.username }}!</H1>
          <br>
          <div class="row">
              <div div class="col-md">
                  <h5 style="text-align: center;">Customers</h5>
                  <hr>
                  <div class="card card-body">
                      <table class="table table-sm">
                          <thead class="thead-dark">
                          <tr>
                              <th>Name</th>
                              <th>Email</th>
                              <th>Steet Address</th>
                              <th>City</th>
                              <th>State</th>
                              <th>Zip Code</th>
                              <th>Weekly Pickup Date</th>
                              <th>Balance</th>
                          </tr>
                          </thead>
                          <tbody>
                          {% for customer in pickup_customers %}
                          <tr>
                              <td>{{ customer.name }}</td>
                              <td>{{ customer.email }}</td>
                              <td>{{ customer.street_address }}</td>
                              <td>{{ customer.city }}</td>
                              <td>{{ customer.state }}</td>
                              <td>{{ customer.zip_code }}</td>
                              <td>{{ customer.weekly_pickup_date }}</td>
                              <td>${{ customer.current_balance }}</td>
                          </tr>
                          {% endfor %}
                          </form>
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>
      </div>
    </div>
  </div>

  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}

{% endblock %}

trash_collector/employees/templates/employees/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    <img width="75px" height="60px"src="{% static 'images/trash.png' %}" alt="logo">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'employees:index' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'employees:daily_view' %}">Daily View</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

trash_collector/employees/templates/employees/pickups.html
{% extends "base.html" %}

{% block content %}
  <h1>Pickups</h1>
  {% if pickup_customers %}
  <ul>
    {% for picks in pickup_customers %}

      <li>
        <a href="{{ employees.pickups }}">{{ picks.name }} {{ picks.street_address }} {{ picks.city }} {{ picks.state }} {{ picks.zip_code }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no pickups today.</p>
  {% endif %}
{% endblock %}