trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/customers/urls.py
from django.urls import path
from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name='create'),
    path('pickup/', views.edit, name='edit'),
    path('detail/', views.detail, name='detail'),
    path('suspend/', views.suspend, name='suspend'),
    path('balance/', views.balance, name='balance')
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (fo
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/customers/models.py
from django.db import models
# Create your models here.

# TODO: Finish customer model by adding necessary properties to fulfill user stories


class Customer(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    street_address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=5) 
    current_balance = models.FloatField(default=0)
    weekly_pickup_date = models.DateField(null=True, blank=True)
    extra_pickup_date = models.DateField(null=True, blank=True)
    start_suspension = models.DateField(null=True, blank=True) 
    end_suspension = models.DateField(null=True, blank=True) 
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    

trash_collector/customers/views.py
from django.core.checks import messages
from django.http import HttpResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Customer
# Create your views here.
#from django.urls import reverse_lazy, reverse
#from django.views import generic

# TODO: Create a function for each path created in customers/urls.py. Each will need a template as well.

def index(request):
    user = request.user
    try:
        logged_in_customer = Customer.objects.get(user=user)
    except Customer.DoesNotExist:
        return HttpResponseRedirect(reverse('customers:create'))
    print(user)
    return render(request, 'customers/index.html')

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        user = request.user
        email = request.POST.get('email')
        city = request.POST.get('city')
        street_address = request.POST.get('street_address')
        state = request.POST.get('state')
        zip_code = request.POST.get('zip_code')
        weekly_pickup_date = request.POST.get('weekly_pickup_date')
        extra_pickup_date = request.POST.get('extra_pickup_date')
        new_cust = Customer(name=name, user=user, email=email, street_address=street_address,
        city=city, state=state, zip_code=zip_code, weekly_pickup_date=weekly_pickup_date,
        extra_pickup_date=extra_pickup_date
        )
        new_cust.save()
        return HttpResponseRedirect(reverse('customers:index'))
    else:
        return render(request, 'customers/create.html')

def edit(request):
    user = request.user
    logged_in_customer = Customer.objects.get(user=user)
    if request.method == "POST":
        logged_in_customer.name = request.POST.get('name')
        logged_in_customer.email = request.POST.get('email')
        logged_in_customer.street_address = request.POST.get('street_address')
        logged_in_customer.city = request.POST.get('city')
        logged_in_customer.state = request.POST.get('state')
        logged_in_customer.zip_code = request.POST.get('zip_code')
        logged_in_customer.weekly_pickup_date = request.POST.get('weekly_pickup_date')
        logged_in_customer.extra_pickup_date = request.POST.get('extra_pickup_date')
        logged_in_customer.save()
        return HttpResponseRedirect(reverse('customers:index'))
    else:
        context = {
            'logged_in_customer': logged_in_customer
    }
    return render(request, 'customers/pickup.html', context)

def detail(request):
    user = request.user
    logged_in_customer = Customer.objects.get(user=user)
    context = {
        'logged_in_customer':logged_in_customer
    }
    return render(request, 'customers/detail.html', context)


def balance(request):
    user = request.user
    logged_in_customer = Customer.objects.get(user=user)
    context = {
        'logged_in_customer':logged_in_customer
    }
    return render(request, 'customers/balance.html', context)

def suspend(request):
    user = request.user
    logged_in_customer = Customer.objects.get(user=user)

    if request.method == "POST":
        logged_in_customer.start_suspension = request.POST.get("start_suspension")
        logged_in_customer.end_suspension = request.POST.get("end_suspension")
        logged_in_customer.save()
        return HttpResponseRedirect(reverse('customers:index'))
    else:
        return render(request, 'customers/suspend.html')

trash_collector/customers/templates/customers/balance.html
{% extends 'base.html' %}

{% block title %} Customer Balance {% endblock %}

{% block header %} <h2>Balance</h2> {% endblock %}

{% block content %}
<form action="{% url 'customers:balance' %}">
        {% csrf_token %}
        <h2>Current balance: ${{logged_in_customer.current_balance}}</h2>
</form>
{% endblock %}

trash_collector/customers/templates/customers/create.html
{% extends 'base.html' %}

{% block title %} Customer Create {% endblock %}

{% block header %} Customer Create {% endblock %}

{% block content %}
<form action="{% url 'customers:create' %}" method="post">
    {% csrf_token %}  
    Name: <input type="text" name='name' id='name'><br />
    Email: <input type="text" name='email' id='email'><br />
    Street Address: <input type="text" name='street_address' id='street_address'><br />
    City: <input type="text" name='city' id='city'><br />
    State: <input type="text" name='state' id='state'><br />
    Zip Code: <input type="text"name='zip_code' id='zip_code'><br />
    Select Weekly Pickup Date: <input type="date"name='weekly_pickup_date' id='weekly_pickup_date'><br />
    Select Extra Pickup Date (optional): <input type="date"name='extra_pickup_date' id='extra_pickup_date'><br />
<input type="submit" value="Submit">
</form>
{% endblock %}

trash_collector/customers/templates/customers/detail.html
{% extends 'base.html' %}

{% block title %} Account Info {% endblock %}

{% block header %} <h2>Account Info</h2> {% endblock %}

{% block content %}
<ul>
<h2>{{logged_in_customer.name}}</h2>
<li><h3>Email: {{logged_in_customer.email}}</h3></li>
<li><h3>Street Address: {{logged_in_customer.street_address}}</h3></li>
<li><h3>City: {{logged_in_customer.city}}</h3></li>
<li><h3>State: {{logged_in_customer.state}}</h3></li>
<li><h3>Zip Code: {{logged_in_customer.zip_code}}</h3></li>
<li><h3>Weekly Pickup Date: {{logged_in_customer.weekly_pickup_date}}</h3></li>
<li><h3>Extra Pickup Date (optional): {{logged_in_customer.extra_pickup_date}}</h3></li>
</ul>
{% endblock %}

trash_collector/customers/templates/customers/index.html
{% extends 'base.html' %}
{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do the same. #}

{% block title %} Customer Home {% endblock %}
{% block header %} <h2>Customer Home</h2> {% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <p>Hello Customer {{ user.username }}!</p>
  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/customers/templates/customers/navbar.html
{% load static%}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    <img width="75px" height="60px"src="{% static 'images/trash.png' %}" alt="logo">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'customers:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'customers:edit' %}">Change Pickup Day</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'customers:detail' %}">Account Info</a>
          <a class="dropdown-item" href="{% url 'customers:suspend' %}">Suspend Pickups</a>
          <a class="dropdown-item" href="{% url 'customers:balance' %}">Current Balance</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

trash_collector/customers/templates/customers/pickup.html
{% extends 'base.html' %}

{% block title %} Change Pickup Day {% endblock %}

{% block header %} Change Pickup Day {% endblock %}

{% block content %}
<form action="{% url 'customers:edit' %}" method="post"> 
    {% csrf_token %}  
    Change Weekly Pickup Date: <input type="date" name='weekly_pickup_date' id='weekly_pickup_date'><br />
    Select or Change Extra Pickup Date (optional): <input type="date" name='extra_pickup_date' id='extra_pickup_date'><br />
<input type="submit" value="Confirm"><br />
<a class="btn btn-sm btn-danger" href="{% url 'customers:index' %}">Exit</a>
</form>
{% endblock %}

trash_collector/customers/templates/customers/suspend.html
{% extends 'base.html' %}

{% block title %} Suspend Account {% endblock %}

{% block header %} Suspend Account {% endblock %}

{% block content %}
<form action="{% url 'customers:suspend' %}" method="post">
        {% csrf_token %}
        Suspend Date From: <input type="date" name='start_suspension' id='start_suspension'>
        To: <input type="date" name='end_suspension' id='end_suspension'><br />
    <input type="submit"></button>
</form>
{% endblock %}